### ISSUE TITLE
Lack of `query:` field for backup should implicitly select whole table

### ISSUE THREAD

**Issue by DanCardin** [schireson/databudgie#34]
```
backup:
  url: <% ENV[DATABUDGIE_BACKUP_URL] %>
  tables:
    *.*:
      location: backups/{table}.yml
```
should implicitly translate to
```
backup:
  url: <% ENV[DATABUDGIE_BACKUP_URL] %>
  tables:
    *.*:
      location: backups/{table}.yml
      query: select * from {table}
```
