### ISSUE TITLE
simplify backup/restore config 

### ISSUE THREAD

**Issue by andrewsosa** [schireson/databudgie#42]
We should be able to set default `location` or `query` directly under the `backup` key, and which would allow us to omit the `name` key in the list of tables. Would result in a config which looks like:

```yaml
backup:
  location: backups/{table}
  query: select * from {table}
  tables:
    - "a.b"
    - "c.x"
    - "f.*"
```

Similarly, we can give `restore` a similar treatment:

```yaml
restore:
  location: backups/{table}
  strategy: use_latest_filename
  truncate: true
  tables:
    - "a.b"
    - "c.x"
    - "f.*"
```

This would be compatible with the current syntax like this:
```yaml
backup:
  location: backups/{table}
  query: select * from {table}
  tables:
    - "public.*"
    - name: other_schema.special_table
      location: s3://special/table/location
      query: select * from {table} where id > 1000
```
