### ISSUE TITLE
`ddl` should be read at the table level

### ISSUE THREAD

**Issue by DanCardin** [schireson/databudgie#58]
Currently

```yaml
ddl:
  enabled: true
  location: ...
```

is read at the backup/restore level. This should instead be a per-table configuration, which is just commonly specified at that level.
