### ISSUE TITLE
named connection list instead of just backup/restore

### ISSUE THREAD

**Issue by andrewsosa** [schireson/databudgie#84]
example config

```yaml
connections:
  named-source:
    url: 
      drivername: postgresql+psycopg2
      username: andrewsosa
      password: foo
      host: localhost
      port: 15432
      database: postgres
    query: select * from {table}
  destination-bar:
    url: postgresql://postgres:postgres@localhost:5432/postgres
    truncate: true

backup:
  target: named-source

restore:
  target: destination-bar
```

usage:

`databudgie backup` uses default `backup.target` value
`databudgie backup --conn named-source` explicitly uses the `source-foo` connection
